DROP DATABASE IF EXISTS highscores;

CREATE DATABASE highscores;

USE highscores;

CREATE TABLE HIGHSCORES (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    SCORE INT DEFAULT 0,
    PRIMARY KEY (ID)
);

INSERT INTO HIGHSCORES (NAME, SCORE) VALUES ('Test Player', 1);